title: "Apurva Bhargava"
description: "Apurva Bhargava's Website"
markdown: kramdown
theme: null
baseurl: ""
url: "https://apurvabhargava.github.io"

author:
  name: "Apurva Bhargava"
  email: "apurvabhargava1762@gmail.com"

nav:
  - name: "About"
    link: "/about"
  - name: "Projects"
    link: "/projects"
  - name: "Substack"
    link: "/blog"
  - name: "CV"
    link: "/pdf/Apurva_Bhargava_CV.pdf"
  - name: "Poetry"
    link: "/poetry"
  - name: "Contact"
    link: "/contact"
